name: Cosmetics
version: ${project.version}
main: com.ilm9001.cosmetics.Cosmetics
api-version: 1.18
authors: [ ilm9001 ]
description: Cosmetics plugin
website: ilm9001.com

commands:
  givecosmetic:
    description: gives a cosmetic
    usage: /givecosmetic <cosmetic> [online player]
    permission: cosmetics.givecosmetic
  refreshcosmetics:
    description: refreshes cosmetic list and gets updated list from config
    usage: /refreshcosmetics
    permission: cosmetics.refresh

permissions:
  cosmetics.givecosmetic:
    description: allows givecosmetic
    default: op
  cosmetics.refresh:
    description: allows refreshing the cosmetics list
    default: op
